### ISSUE TITLE
topics mit gleichem Wortstamm oder Silbenbeginn

### ISSUE THREAD

**Issue by JanetteSeuffert** [Freischuetz-Digital/topicMapViz#11]
bei Topics, die einen gleichem Wortstamm oder Silbenbeginn haben, werden in dem Graph gleichzeitig angezeigt.
siehe z.B.: 
"braut" und "brautjungfern", "elf" und "elfriede", "wald" und "Waldvögel", "Wind" und "winden", "wildes Heer" und "Wildschwein" etc

**Comment by bwbohl** [comment]
is identical with #14
