### ISSUE TITLE
Occurences

### ISSUE THREAD

**Issue by JanetteSeuffert** [Freischuetz-Digital/topicMapViz#12]
Occurences (<occurrence> … </occurrence>):  
Die Anzahl und eine Auflistung der Texte, in denen der erwählte Topic vorkommt, wird gezeigt, mit der Möglichkeit der Filterung:
durch eine Auswahlbox gewählte Texte zeigen alle Stellen, d.h. die Zeilen, lines bzw. Wörter (nach <lb/>) des Textes, die den Begriff beinhalten. Dabei soll der Kontext der Textstelle berücksichtigt werden (line oder mehrere lines)

**Comment by bwbohl** [comment]
textstellen werden nun angezeigt

das mit der filterung verstehe ich nicht, kannst du das näher beschreiben?

**Comment by JanetteSeuffert** [comment]
done
