### ISSUE TITLE
Abstand nach den Fundstellen

### ISSUE THREAD

**Issue by JanetteSeuffert** [Freischuetz-Digital/topicMapViz#38]
… etwas erweitern

**Comment by bwbohl** [comment]
kannst Du das etwas konkretisieren?
Mir mag nicht mehr einfallen, was damit gemeint war...

**Comment by JanetteSeuffert** [comment]
der Abstand von der letzten Fundstelle zu dem untersten Rand sollte (v.a. später in der EO) vielleicht etwas größer sein

> Am 25.06.2015 um 12:24 schrieb Benjamin W. Bohl notifications@github.com:
> 
> kannst Du das etwas konkretisieren?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/Freischuetz-Digital/topicMapViz/issues/38#issuecomment-115202553.

Janette Seuffert, M.A. | Wissenschaftliche Mitarbeiterin
OPERA - Spektrum des europäischen Musiktheaters in Einzeleditionen | Freischütz Digital
Institut für Musikwissenschaft | Goethe-Universität Frankfurt | Senckenberganlage 31-33 | 60325 Frankfurt am Main
Tel. 069/798-22164 | Fax: 069/798-22170 | E-Mail: seuffert@em.uni-frankfurt.de mailto:seuffert@em.uni-frankfurt.de

http://www.opera.adwmainz.de http://www.opera.adwmainz.de/
