### ISSUE TITLE
some sources do not appear in occurrence list with certain topics

### ISSUE THREAD

**Issue by bwbohl** [Freischuetz-Digital/topicMapViz#49]

**Comment by bwbohl** [comment]
this has to be tested and I need precise examples in order to be able to debug. Can you handle that @JanetteSeuffert ?

**Comment by bwbohl** [comment]
I'll provide you with a new release before you start work, though.

**Comment by JanetteSeuffert** [comment]
sources do appear now in the occurence list on:
http://rubin.upb.de:8092/exist/apps/topicMapViz/index.html

**Comment by bwbohl** [comment]
Ok, then it's fine to close this issue?

**Comment by JanetteSeuffert** [comment]
ja
